apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kurbits.fullname" . }}
  labels:
    {{- include "kurbits.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ required "app.secretKey must be set" .Values.app.secretKey | quote }}
  DATABASE_URL: {{ include "kurbits.databaseUrl" . | quote }}
