"""
Creates a sibling representation containing extracted text as a .txt file.
Called after successful OCR or Whisper transcription.
"""
from __future__ import annotations
import os
import logging
from datetime import datetime, timezone

log = logging.getLogger(__name__)

TRANSCRIPTION_TYPE_NAME  = 'Transcription'
TRANSCRIPTION_TYPE_LABEL = 'Transcription'


def create_text_representation(
    node_id: int,
    institution_id: int,
    source_filename: str,
    text: str,
    method: str,          # 'ocr' | 'whisper'
    upload_folder: str,
    uploaded_by_id: int,
) -> bool:
    """
    Creates a new 'Transcription' representation with the extracted text
    as a .txt file. Returns True on success.
    """
    try:
        from app.extensions import db
        from app.models.node import Node, NodeAttachment
        from app.models.representation import NodeRepresentation, RepresentationType

        node = Node.query.get(node_id)
        if not node:
            log.warning(f'create_text_representation: node {node_id} not found')
            return False

        # ── Find or create the RepresentationType ─────────────────────
        rep_type = RepresentationType.query.filter_by(
            institution_id=institution_id,
            name=TRANSCRIPTION_TYPE_NAME,
        ).first()

        if not rep_type:
            rep_type = RepresentationType(
                institution_id=institution_id,
                name=TRANSCRIPTION_TYPE_NAME,
                description=TRANSCRIPTION_TYPE_LABEL,
            )
            db.session.add(rep_type)
            db.session.flush()
            log.info(f'Created RepresentationType "{TRANSCRIPTION_TYPE_NAME}" for institution {institution_id}')

        # ── Build label for the representation ─────────────────────────
        base_name = source_filename.rsplit('.', 1)[0]
        method_label = 'OCR' if method == 'ocr' else 'Whisper'
        rep_label = f'{base_name} ({method_label})'

        # ── Create the representation ──────────────────────────────────
        representation = NodeRepresentation(
            node_id=node_id,
            rep_type_id=rep_type.id,
            label=rep_label,
            note=f'Automatically generated by {method_label} text extraction.',
        )
        db.session.add(representation)
        db.session.flush()

        # ── Write text to disk as .txt ─────────────────────────────────
        upload_dir = os.path.join(upload_folder, str(institution_id), str(node_id))
        os.makedirs(upload_dir, exist_ok=True)

        import uuid
        stored_filename  = f'{uuid.uuid4().hex}_{base_name}_transcription.txt'
        original_filename = f'{base_name}_transcription.txt'
        file_path = os.path.join(upload_dir, stored_filename)

        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(text)

        file_size = os.path.getsize(file_path)

        # ── Create NodeAttachment linked to the representation ─────────
        attachment = NodeAttachment(
            node_id=node_id,
            representation_id=representation.id,
            filename=stored_filename,
            original_filename=original_filename,
            file_size=file_size,
            mime_type='text/plain',
            uploaded_by_id=uploaded_by_id,
            uploaded_at=datetime.now(timezone.utc),
            extracted_text=text,
            extracted_text_at=datetime.now(timezone.utc),
        )
        db.session.add(attachment)
        db.session.commit()

        log.info(
            f'Created Transcription representation {representation.id} '
            f'for node {node_id} from {source_filename}'
        )
        return True

    except Exception as e:
        log.exception(f'Failed to create text representation for node {node_id}: {e}')
        try:
            from app.extensions import db
            db.session.rollback()
        except Exception:
            pass
        return False