"""inital migration

Revision ID: 3465091ade44
Revises: 
Create Date: 2026-09-26 19:45:39.450739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3465091ade44'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('country_code', sa.String(length=10), nullable=False),
    sa.Column('institution_code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_code', 'institution_code', name='uq_institution_ref'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('is_system_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('active_institution_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['active_institution_id'], ['institutions.id'], name='fk_user_active_institution', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('agent_node_relation_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('is_symmetric', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('complementary_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['complementary_id'], ['agent_node_relation_types.id'], name='fk_agent_node_relation_complementary', use_alter=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'name', name='uq_agent_node_relation_type_per_institution')
    )
    op.create_table('agent_relation_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('is_symmetric', sa.Boolean(), nullable=False),
    sa.Column('complementary_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['complementary_id'], ['agent_relation_types.id'], name='fk_agent_relation_complementary', use_alter=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'name', name='uq_agent_relation_type_per_institution')
    )
    op.create_table('agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('agent_type', sa.Enum('PERSON', 'ORGANIZATION', 'FAMILY', 'SOFTWARE', name='agenttype'), nullable=False),
    sa.Column('authorized_form', sa.String(length=300), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_from', sa.String(length=50), nullable=True),
    sa.Column('date_to', sa.String(length=50), nullable=True),
    sa.Column('identifier', sa.String(length=200), nullable=True),
    sa.Column('website', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name='fk_agent_created_by'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('background_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('background_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_background_tasks_institution_id'), ['institution_id'], unique=False)

    op.create_table('bookmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('subtitle', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'institution_id', 'entity_type', 'entity_id', name='uq_bookmark_user_entity')
    )
    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookmarks_user_id'), ['user_id'], unique=False)

    op.create_table('delivery_checklist_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('delivery_method', sa.String(length=50), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('external_integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('search_path', sa.String(length=500), nullable=False),
    sa.Column('headers', sa.JSON(), nullable=True),
    sa.Column('result_path', sa.String(length=200), nullable=False),
    sa.Column('field_mappings', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'name', name='uq_integration_name_per_institution')
    )
    op.create_table('hierarchy_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('entity_type', sa.Enum('RESOURCE', 'LOCATION', 'CLASSIFICATION', name='hierarchyentitytype'), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'name', name='uq_hierarchy_type_per_institution')
    )
    op.create_table('identifier_schemes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('url_template', sa.String(length=500), nullable=True),
    sa.Column('generator_url', sa.String(length=500), nullable=True),
    sa.Column('generator_headers', sa.JSON(), nullable=True),
    sa.Column('generator_body_template', sa.JSON(), nullable=True),
    sa.Column('generator_response_path', sa.String(length=200), nullable=True),
    sa.Column('generator_shoulder', sa.String(length=200), nullable=True),
    sa.Column('target_url_template', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'name', name='uq_identifier_scheme_per_institution')
    )
    op.create_table('institution_ai_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('whisper_service_url', sa.String(length=512), nullable=False),
    sa.Column('whisper_api_key', sa.Text(), nullable=False),
    sa.Column('whisper_model', sa.String(length=256), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('institution_ai_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_institution_ai_config_institution_id'), ['institution_id'], unique=True)

    op.create_table('label_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('format_key', sa.String(length=60), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('elements', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name='fk_label_template_updated_by'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'name', name='uq_label_template_name')
    )
    op.create_table('metadata_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'name', 'entity_type', name='uq_metadata_template_per_institution')
    )
    op.create_table('node_relation_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('is_symmetric', sa.Boolean(), nullable=False),
    sa.Column('complementary_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['complementary_id'], ['node_relation_types.id'], name='fk_node_relation_complementary'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'name', name='uq_node_relation_type_per_institution')
    )
    op.create_table('place_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('applicable_to', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'name', name='uq_place_type_per_institution')
    )
    op.create_table('recent_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('subtitle', sa.String(length=200), nullable=True),
    sa.Column('viewed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'institution_id', 'entity_type', 'entity_id', name='uq_recent_item_user_entity')
    )
    with op.batch_alter_table('recent_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recent_items_user_id'), ['user_id'], unique=False)

    op.create_table('records_vocabulary_terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=40), nullable=False),
    sa.Column('value', sa.String(length=120), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'field', 'value', name='uq_records_vocab_term')
    )
    with op.batch_alter_table('records_vocabulary_terms', schema=None) as batch_op:
        batch_op.create_index('ix_records_vocab_field', ['institution_id', 'field'], unique=False)

    op.create_table('representation_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'name', name='uq_rep_type_per_institution')
    )
    op.create_table('saved_searches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'institution_id', 'name', name='uq_saved_search_user_name')
    )
    op.create_table('tag_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('applicable_to', sa.String(length=20), server_default='both', nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'name', name='uq_tag_category_per_institution')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'name', name='uq_tag_per_institution')
    )
    op.create_table('user_institution_association',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'institution_id')
    )
    op.create_table('agent_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_identifiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('scheme_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name='fk_agent_identifier_created_by'),
    sa.ForeignKeyConstraint(['scheme_id'], ['identifier_schemes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scheme_id', 'value', name='uq_agent_identifier_value_per_scheme')
    )
    with op.batch_alter_table('agent_identifiers', schema=None) as batch_op:
        batch_op.create_index('ix_agent_identifiers_agent', ['agent_id'], unique=False)

    op.create_table('agent_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('note_type', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_places',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('place_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('wikidata_id', sa.String(length=50), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('date_from', sa.String(length=20), nullable=True),
    sa.Column('date_to', sa.String(length=20), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_tags',
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_id', 'tag_id')
    )
    op.create_table('agent_to_agent_association',
    sa.Column('source_agent_id', sa.Integer(), nullable=False),
    sa.Column('target_agent_id', sa.Integer(), nullable=False),
    sa.Column('association_type', sa.String(length=100), nullable=False),
    sa.CheckConstraint('source_agent_id != target_agent_id', name='no_self_agent_relation'),
    sa.ForeignKeyConstraint(['source_agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_agent_id', 'target_agent_id')
    )
    op.create_table('classifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('level_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scope_note', sa.Text(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('version_label', sa.String(length=50), nullable=True),
    sa.Column('bpmn_xml', sa.Text(), nullable=True),
    sa.Column('hierarchy_type_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name='fk_classification_created_by'),
    sa.ForeignKeyConstraint(['hierarchy_type_id'], ['hierarchy_types.id'], name='fk_classification_hierarchy_type'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['classifications.id'], name='fk_classification_parent', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'parent_id', 'institution_id', name='uq_classification_code_per_parent')
    )
    op.create_table('hierarchy_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hierarchy_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('can_have_location', sa.Boolean(), nullable=False),
    sa.Column('is_object_level', sa.Boolean(), nullable=False),
    sa.Column('metadata_schema', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hierarchy_type_id'], ['hierarchy_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hierarchy_type_id', 'name', name='uq_level_name_per_type')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('level_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('can_store_nodes', sa.Boolean(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('location_type', sa.String(length=30), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('hierarchy_type_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hierarchy_type_id'], ['hierarchy_types.id'], name='fk_location_hierarchy_type'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['locations.id'], name='fk_location_parent', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'parent_id', 'institution_id', name='uq_location_code_per_parent')
    )
    op.create_table('submission_agreements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('agreement_date', sa.Date(), nullable=True),
    sa.Column('review_date', sa.Date(), nullable=True),
    sa.Column('delivery_schedule', sa.Text(), nullable=True),
    sa.Column('scope_and_content', sa.Text(), nullable=True),
    sa.Column('access_conditions', sa.Text(), nullable=True),
    sa.Column('appraisal_notes', sa.Text(), nullable=True),
    sa.Column('disposition_authority', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bpmn_task_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diagram_classification_id', sa.Integer(), nullable=False),
    sa.Column('linked_classification_id', sa.Integer(), nullable=True),
    sa.Column('task_bpmn_id', sa.String(length=120), nullable=False),
    sa.Column('task_label', sa.String(length=300), nullable=True),
    sa.Column('retention_period', sa.String(length=120), nullable=True),
    sa.Column('retention_rule', sa.String(length=200), nullable=True),
    sa.Column('disposal_action', sa.String(length=120), nullable=True),
    sa.Column('security_class', sa.String(length=120), nullable=True),
    sa.Column('medium_format', sa.String(length=120), nullable=True),
    sa.Column('legal_basis', sa.String(length=300), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('produced_by', sa.String(length=500), nullable=True),
    sa.Column('used_by', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['diagram_classification_id'], ['classifications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['linked_classification_id'], ['classifications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bpmn_task_links', schema=None) as batch_op:
        batch_op.create_index('ix_bpmn_task_links_diagram', ['diagram_classification_id'], unique=False)
        batch_op.create_index('ix_bpmn_task_links_linked', ['linked_classification_id'], unique=False)

    op.create_table('classification_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classification_id', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('before_data', sa.JSON(), nullable=False),
    sa.Column('after_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['classification_id'], ['classifications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('submission_agreement_id', sa.Integer(), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('delivery_method', sa.String(length=50), nullable=True),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('received_by_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('item_count', sa.Integer(), nullable=True),
    sa.Column('physical_extent', sa.String(length=300), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('checklist', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['received_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submission_agreement_id'], ['submission_agreements.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hierarchy_level_relationships',
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('parent_id != child_id', name='no_self_reference_level'),
    sa.ForeignKeyConstraint(['child_id'], ['hierarchy_levels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['hierarchy_levels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parent_id', 'child_id')
    )
    op.create_table('nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('local_ref', sa.String(length=100), nullable=False),
    sa.Column('ref_code', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('level_of_description', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_start', sa.Date(), nullable=True),
    sa.Column('date_end', sa.Date(), nullable=True),
    sa.Column('date_certainty', sa.String(length=50), nullable=True),
    sa.Column('extent', sa.String(length=200), nullable=True),
    sa.Column('scope_and_content', sa.Text(), nullable=True),
    sa.Column('arrangement', sa.Text(), nullable=True),
    sa.Column('access_conditions', sa.Text(), nullable=True),
    sa.Column('reproduction_conditions', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=100), nullable=True),
    sa.Column('finding_aids', sa.Text(), nullable=True),
    sa.Column('current_location_id', sa.Integer(), nullable=True),
    sa.Column('metadata_spec', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'RESTRICTED', name='nodestatus'), nullable=False),
    sa.Column('hierarchy_type_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('top_node_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name='fk_node_created_by'),
    sa.ForeignKeyConstraint(['current_location_id'], ['locations.id'], name='fk_node_current_location', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hierarchy_type_id'], ['hierarchy_types.id'], name='fk_node_hierarchy_type'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['nodes.id'], name='fk_node_parent', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['top_node_id'], ['nodes.id'], name='fk_node_top_node', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name='fk_node_updated_by'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('local_ref', 'parent_id', 'institution_id', name='uq_local_ref_per_parent'),
    sa.UniqueConstraint('ref_code')
    )
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.create_index('ix_nodes_institution_parent', ['institution_id', 'parent_id'], unique=False)
        batch_op.create_index('ix_nodes_parent_local_ref', ['parent_id', 'local_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_nodes_top_node_id'), ['top_node_id'], unique=False)

    op.create_table('submission_agreement_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_agreement_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=200), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['submission_agreement_id'], ['submission_agreements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('delivery_id', sa.Integer(), nullable=True),
    sa.Column('submission_agreement_id', sa.Integer(), nullable=True),
    sa.Column('accession_number', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('date_received', sa.Date(), nullable=True),
    sa.Column('date_accessioned', sa.Date(), nullable=True),
    sa.Column('creator_agent_id', sa.Integer(), nullable=True),
    sa.Column('extent', sa.String(length=300), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('appraisal_decision', sa.Text(), nullable=True),
    sa.Column('disposition_notes', sa.Text(), nullable=True),
    sa.Column('access_restrictions', sa.Text(), nullable=True),
    sa.Column('processing_notes', sa.Text(), nullable=True),
    sa.Column('accessioned_by_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['accessioned_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creator_agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_agreement_id'], ['submission_agreements.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_node_association',
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_id', 'node_id')
    )
    op.create_table('classification_node_association',
    sa.Column('classification_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['classification_id'], ['classifications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('classification_id', 'node_id')
    )
    op.create_table('location_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('condition_note', sa.Text(), nullable=True),
    sa.Column('expected_return', sa.Date(), nullable=True),
    sa.Column('from_location_id', sa.Integer(), nullable=True),
    sa.Column('moved_at', sa.DateTime(), nullable=False),
    sa.Column('moved_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['from_location_id'], ['locations.id'], name='fk_lm_from_location', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['moved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location_node_association',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'node_id')
    )
    op.create_table('node_association',
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(length=100), nullable=False),
    sa.CheckConstraint('source_id != target_id', name='no_self_association'),
    sa.ForeignKeyConstraint(['source_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_id', 'target_id')
    )
    op.create_table('node_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('before_data', sa.JSON(), nullable=False),
    sa.Column('after_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('node_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('flag_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('resolved_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('node_identifiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('scheme_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name='fk_node_identifier_created_by'),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scheme_id'], ['identifier_schemes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scheme_id', 'value', name='uq_identifier_value_per_scheme')
    )
    with op.batch_alter_table('node_identifiers', schema=None) as batch_op:
        batch_op.create_index('ix_node_identifiers_node', ['node_id'], unique=False)

    op.create_table('node_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('note_type', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('node_places',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('place_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('wikidata_id', sa.String(length=50), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('date_from', sa.String(length=20), nullable=True),
    sa.Column('date_to', sa.String(length=20), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('node_representations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('rep_type_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rep_type_id'], ['representation_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('node_tags',
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('node_id', 'tag_id')
    )
    op.create_table('accession_nodes',
    sa.Column('accession_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['accession_id'], ['accessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('accession_id', 'node_id')
    )
    op.create_table('node_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('checksum_md5', sa.String(length=32), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('pronom_id', sa.String(length=20), nullable=True),
    sa.Column('image_width', sa.Integer(), nullable=True),
    sa.Column('image_height', sa.Integer(), nullable=True),
    sa.Column('image_dpi_x', sa.Float(), nullable=True),
    sa.Column('image_dpi_y', sa.Float(), nullable=True),
    sa.Column('image_mode', sa.String(length=20), nullable=True),
    sa.Column('image_bit_depth', sa.Integer(), nullable=True),
    sa.Column('exif_data', sa.JSON(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('av_codec', sa.String(length=100), nullable=True),
    sa.Column('av_bitrate', sa.Integer(), nullable=True),
    sa.Column('thumbnail_path', sa.String(length=500), nullable=True),
    sa.Column('tech_extracted_at', sa.DateTime(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('extracted_text_at', sa.DateTime(), nullable=True),
    sa.Column('representation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['representation_id'], ['node_representations.id'], name='fk_attachment_representation', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('node_attachments')
    op.drop_table('accession_nodes')
    op.drop_table('node_tags')
    op.drop_table('node_representations')
    op.drop_table('node_places')
    op.drop_table('node_notes')
    with op.batch_alter_table('node_identifiers', schema=None) as batch_op:
        batch_op.drop_index('ix_node_identifiers_node')

    op.drop_table('node_identifiers')
    op.drop_table('node_flags')
    op.drop_table('node_changes')
    op.drop_table('node_association')
    op.drop_table('location_node_association')
    op.drop_table('location_movements')
    op.drop_table('classification_node_association')
    op.drop_table('agent_node_association')
    op.drop_table('accessions')
    op.drop_table('submission_agreement_attachments')
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nodes_top_node_id'))
        batch_op.drop_index('ix_nodes_parent_local_ref')
        batch_op.drop_index('ix_nodes_institution_parent')

    op.drop_table('nodes')
    op.drop_table('hierarchy_level_relationships')
    op.drop_table('deliveries')
    op.drop_table('classification_changes')
    with op.batch_alter_table('bpmn_task_links', schema=None) as batch_op:
        batch_op.drop_index('ix_bpmn_task_links_linked')
        batch_op.drop_index('ix_bpmn_task_links_diagram')

    op.drop_table('bpmn_task_links')
    op.drop_table('submission_agreements')
    op.drop_table('locations')
    op.drop_table('hierarchy_levels')
    op.drop_table('classifications')
    op.drop_table('agent_to_agent_association')
    op.drop_table('agent_tags')
    op.drop_table('agent_places')
    op.drop_table('agent_notes')
    with op.batch_alter_table('agent_identifiers', schema=None) as batch_op:
        batch_op.drop_index('ix_agent_identifiers_agent')

    op.drop_table('agent_identifiers')
    op.drop_table('agent_attachments')
    op.drop_table('user_institution_association')
    op.drop_table('tags')
    op.drop_table('tag_categories')
    op.drop_table('saved_searches')
    op.drop_table('representation_types')
    with op.batch_alter_table('records_vocabulary_terms', schema=None) as batch_op:
        batch_op.drop_index('ix_records_vocab_field')

    op.drop_table('records_vocabulary_terms')
    with op.batch_alter_table('recent_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recent_items_user_id'))

    op.drop_table('recent_items')
    op.drop_table('place_types')
    op.drop_table('node_relation_types')
    op.drop_table('metadata_templates')
    op.drop_table('label_templates')
    with op.batch_alter_table('institution_ai_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_institution_ai_config_institution_id'))

    op.drop_table('institution_ai_config')
    op.drop_table('identifier_schemes')
    op.drop_table('hierarchy_types')
    op.drop_table('external_integrations')
    op.drop_table('delivery_checklist_templates')
    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookmarks_user_id'))

    op.drop_table('bookmarks')
    with op.batch_alter_table('background_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_background_tasks_institution_id'))

    op.drop_table('background_tasks')
    op.drop_table('agents')
    op.drop_table('agent_relation_types')
    op.drop_table('agent_node_relation_types')
    op.drop_table('users')
    op.drop_table('institutions')
    # ### end Alembic commands ###
